Fixed incompatible .NET Version

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -62,6 +62,15 @@ jobs:
     - name: Login to DockerHub
       run: |
         echo "${{ env.DOCKER_TOKEN }}" | docker login -u "${{ env.DOCKER_USERNAME }}" --password-stdin
+      continue-on-error: true
+
+    - name: Verify Docker Login
+      run: |
+        if ! docker info | grep -q "Username: ${{ env.DOCKER_USERNAME }}"; then
+          echo "Docker login failed. Please check your credentials."
+          exit 1
+        fi
+        echo "Docker login successful!"
 
     - name: Build and push Docker image
       uses: docker/build-push-action@v4
